name: 'setup-xcodegen'
description: 'Installs the xcodegen tool and enables cache'
branding:
  icon: briefcase
  color: blue
inputs:
  enable-cache:
    description: 'Cache or not the installation'
    default: 'true'
    required: false
  version:
    description: 'The version of xcodegen to be used. Check https://github.com/yonaskolb/XcodeGen/releases for valid options.'
    default: latest
    required: false
runs:
  using: 'node12'
  main: 'index.js'
